### ISSUE TITLE
Move Estimating Cost section TO sit under Resources, FROM under 'Getting Started with ReproNim'

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#101]
I thought I should file an issue, rather than rely on email only, especially since my email was not as clear to all as I had intended - and here I just include the change to move the Estimating Cost page to the bottom item on the Resources list. 

MOVE Estimating Cost page, as below

Change to:    (As seen on Left Margin Menu)

Resources  			dev.repronim.org/resources/
>Getting Started with ReproNim	 	dev.repronim.org/resources/getting-started/
>Training					dev.repronim.org/resources/training/
>Tutorials					dev.repronim.org/resources/tutorials/
>Tools						dev.repronim.org/resources/tools/
>Estimating Cost				dev.repronim.org/resources/getting-started/estimating-cost/

**Comment by asmacdo** [comment]
closed by https://github.com/ReproNim/repronim.org/pull/100 (I did this at the same time as removing implementations)
