### ISSUE TITLE
Principle numbering:  letters or numbers

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#105]
The ReproPrinciples were labeled 1.a, b, c in the Google Doc but are now 1.1, 2 etc. Except they aren't written as 1.1, 1.2, but just single numbers (see https://main--repronim.netlify.app/about/why/#repronims-principles-of-reproducible-neuroimaging).  It's OK if they are numbers, but we'll have to change references accordingly.  But it would be better if they were 1.1, 1.2 etc.

**Comment by chaselgrove** [comment]
I like the original (number.letter) that we had and have updated them to that scheme.
