### ISSUE TITLE
Split "why reproducible neuromaging"

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#115]
Our "why reproducible neuroimaging" page has a lot of "what" on it; specifically, I couldn't find the list of principles because I didn't think to look for them under "why."

I propose splitting this page.  Perhaps the initial "what is reproducible neuromaing" is happy where it is as a complement to the initial "why," but I'd suggest separate pages for "what does reproducible neuroimaging look like in practice" (including the principles) and "how does ReproNim support reproducbile neuroimaging."

Simply separating these out makes for a lot of options under "About."  One way to address this is to separate "about repronim" from "about reproducible neuroimaging," but this is secondary to exposing some of the content hiding out under "why."

**Comment by memartone** [comment]
I'm more than happy to have them as separate pages.  I changed the header structure so I could at least link to the different pieces.  But I won't do anymore linking if you want to split them up.

**Comment by chaselgrove** [comment]
I split that out under the About section.  It's a busy section now, but I think it's easier to find information.  We can roll this back or work the structure further as needed -- I'll leave this issue open until we've settled.

And please don't be shy about linking at this stage.  If I break a link by moving something it's easy to detect and fix.

**Comment by chaselgrove** [comment]
Email discussion approves; closing.
