### ISSUE TITLE
Add ecosystem photo to resources

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/repronim.org#12]
- [ ] Get the original ecosystem photo then reassign to asmacdo

**Comment by memartone** [comment]
I downloaded this from the original website.  Will this do?  
![ReproSystem](https://github.com/user-attachments/assets/aa2e3bef-c026-4c6a-8db5-04f234be6dd5)

**Comment by memartone** [comment]
@asmacdo I can't seem to assign this to you in the side menu.  According to the directions, I'm supposed to be able to click on the field and then type your name, but it is unclickable.

**Comment by asmacdo** [comment]
@chaselgrove are you an admin for this repo? Could you please add me as an admin, and optionally add @memartone and @juliebates as "triage" (Or I can do this after being made an admin)

We can bump privileges from "triage" to "write" once you feel comfortable with the workflows?

**Comment by asmacdo** [comment]
@memartone Originally this was going to go here https://dev.repronim.org/resources/ecosystem/

But IIRC, in one of our meetings we decided not to keep that page. Since you've included this image in https://github.com/ReproNim/repronim.org/issues/50 I'll just close this one. Please reopen if I missed something.
