### ISSUE TITLE
Add tutorials introductory content

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#124]
Add content to top-level tutorials page.

**Comment by memartone** [comment]
Christian, I can take a stab at this.

**Comment by chaselgrove** [comment]
@memartone thanks!  I've added that but will leave this ticket open so we can consider if we want to comment on the tutorials themselves once they're finalized.

**Comment by memartone** [comment]
@chaselgrove I'm going to add the list of tutorials to this page as the links on the side don't really give you what the tutorial is for.  I'm not sure if we can change the labels, so this will be a placeholder.

**Comment by chaselgrove** [comment]
Closed via #150.
