### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#17]
I'm not clear on how the category 'Tutorials' inter-relates with Training Materials here.
The Tutorials button significantly emphasizes the category, does that fit with our materials?
One thing that does pop out at me here is a reminder that we currently have guides for 'How would ReproNim do...' that I don't think are included here or in the mock up slide set - do we want to use these on the development site?

**Comment by asmacdo** [comment]
I think we are clear for now on how this will be laid out for initial implementation. We can discuss moving things around in the future, but for now I think we can consider this closed.
