### ISSUE TITLE
Tutorials section appears under 'Documentation', based on top navigaton indication

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#18]
This is just a note! I know it is all a draft, but just mentioning it while I see it, because backing out of Tutorials leads to 'Tools', so the navigation in and out respectively implies different (confusing) nested organizational frameworks.

**Comment by asmacdo** [comment]
IIUC we've discussed this since this issue was raised, and is no longer a problem. @juliebates please reopen if I've missed something.

**Comment by juliebates** [comment]
Backing out of Tutorials no longer leads to Tools for me either. 
I do notice some other things which may or not be relevant: 
-The Tutorials button on the main page is not active, it points to a 404 error page
-Getting Started with ReproNim button goes forward to Tutorials via a Left margin Navigation list that includes Tutorials
-From within the Tutorials main window, (which is currently a brief list of How to....), the top horizontal 'directory tree' shows Resources > Tutorials.  (thiat isn't how I got there, but that may be fine, it may be how you want user to orient)
-but also note that if I hit the back arrow from that preliminary list window, it takes me to the actual DICOM to BIDS tutorial)
--and then if I back out another step from the full DICOM to BIDS tutorial, it takes me to the 'Getting Started with ReproNim' window, which by the way shows as beign a subsidiary of Resources.

I'm not sure which if any of those things are helpful, i"m just relaying my observations in the moment, but I also realize that things are actively in development and likely to move around
