### ISSUE TITLE
Find a single home for the tools section

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#29]
Tools are listed at /resources/ but this also links to the tools list at /resources/tools/.  They should have one home.

Currently the content at /resources/tools/ is authoritative and that at /resources/ is outdated.

**Comment by asmacdo** [comment]
It might make sense to keep the /resources/ list since it provides a brief overview of each so the user doesn't have to inspect every page. 

Also, AFAICT the /resources/ list looks correct.

**Comment by asmacdo** [comment]
Ah I think you fixed this with https://github.com/ReproNim/repronim.org/pull/30

Ill close for now, reopen if i missed something.

**Comment by chaselgrove** [comment]
Will be fixed by #41 

Okay to leave this closed.
