### ISSUE TITLE
Update tools leftnav

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#31]
Match leftnav Tools under /resources/ to the list at /resources/tools/.

**Comment by chaselgrove** [comment]
How can these be ordered to match the list in the content?

**Comment by asmacdo** [comment]
We can add weights in the title header for each page. This is how we've ordered the Reources section. Lower numbers are placed first.

```
---
title: Getting Started with ReproNim
weight: 2
---
```
