### ISSUE TITLE
Port fellows resources

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/repronim.org#36]
Port the page, and fixup the fellowship page  todo link

Take a [Look](TODO link) at some of the many things our Fellows have done!

**Comment by juliebates** [comment]
Here is the (TODO link) : https://www.repronim.org/fellows-resources

**Comment by asmacdo** [comment]
@juliebates I assume fellows-resources needs to be ported over? Updating the title, please correct me if I'm mistaken.

**Comment by juliebates** [comment]
Yes, I forgot that the page had not yet been ported over. 
I'm not clear what title change is needed?

**Comment by asmacdo** [comment]
The title change is done, it was just to fix the link. now it is to port the page
