### ISSUE TITLE
TODO: Add this image to "Why reproducible neuroimaging"

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#45]
After the 4 core actions and before the "How does ReproNim support reproducible neuroimaging" section
![ReproNIM Website Mock Up](https://github.com/user-attachments/assets/9323c576-4bc8-4b06-9c6f-597c78c1adce)

**Comment by asmacdo** [comment]
https://dev.repronim.org/about/why/

I've added it, but the image is low resolution (a bit fuzzy) and the margins are a big. I'll close for now, but if you can get a better image we should replace
