### ISSUE TITLE
TODO:  Fix sizing on user persona images

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#47]
Here are all the original images for the user personas.  I think they are all close to the same size now, within a pixel or two. 
![John](https://github.com/user-attachments/assets/53bc1ee7-2536-495f-9de1-0eed7c644011)
![Richard](https://github.com/user-attachments/assets/d34afb9c-de51-4da5-9222-d4633fad449b)
![Sarah](https://github.com/user-attachments/assets/8a71c919-95ac-456f-af85-c30c0be7cc0f)
![Evelyn](https://github.com/user-attachments/assets/1fb89c08-90da-4a70-9cd0-1104f6334f1e)

**Comment by asmacdo** [comment]
@memartone these (especially John and Evelyn) look stretched.

**Comment by memartone** [comment]
Back to the drawing board...

**Comment by memartone** [comment]
OK, how about these
![John not squished (4)](https://github.com/user-attachments/assets/247bf182-1ed4-43e7-8dc3-3a6de0bad07d)
![Evelyn](https://github.com/user-attachments/assets/1a19ccc7-bd98-432f-90be-3a67087041e8)
![Sarah](https://github.com/user-attachments/assets/4d9613c0-ee8e-43c2-b394-f67ac000e183)
![Richard](https://github.com/user-attachments/assets/856e9e09-5765-426c-a70d-9fc7b7159de9)
