### ISSUE TITLE
Port over the team info

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/repronim.org#56]
Port over from https://www.repronim.org/about_us.html  to `/about/team/`
 - ReproNim Leadership
 - Our Current Full Team by Site
 - Directory (gallery)

**Comment by chaselgrove** [comment]
See TODO in about/team.

**Comment by juliebates** [comment]
I discussed the gallery question with Dave- for this gallery (the ReproNIm Directory) -- OK to NOT include the gallery
