### ISSUE TITLE
RE: Webinar Series under About Us

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#62]
My original intent was to use the Webinar Series page (https://www.repronim.org/webinar-series.html), rather than the youtube channel in this location.  

I am guessing, and can see why you replaced that page with the youtube channel, because it is an active step.

My reasoning was that The youtube page itself is a cluttered thing when people are looking for an overview on topics, speaker background/context, which was why I was pointing to the Webinars page, which I know some people use often. However, I have not yet come up with any satisfactory simple and ultra brief phrase that neatly enables both links in this location (which I think is your 'Port over webinar series #58) issue.... 

Maybe for now leave as it is, can be a discussion point. We do need the webinars page somewhere, and I reference it in the Training Section. I'll give it more thought!

**Comment by asmacdo** [comment]
@juliebates wdyt about

- Follow our webinar series (link to ported page)
- Check out our YouTube Channel(link)

Its not exactly the same, but I suppose its more accurate. 

FWIW, we also do have a webinar playlist but it doesnt look like its being updated.
https://www.youtube.com/playlist?list=PLs3CA4ShM1DUX0nTMKfoB8Z6kdrZpByLa

**Comment by juliebates** [comment]
I'd say ignore the webinar playlist on youtube

re: Webinar Series 

Here is a slightly different idea, it just occurred to me, see what you think.
1) leave the youtube link you have for following the webinar series, 
but
2)Add a very brief section for the Webinar Series, just below the ReproNim/INCF Fellows bit, and just above the 'Join the ReproNim Community' section per below, and port the webinars page to this section. The webinar series has a pretty good following and is an important front facing part of our public repertoire- and just having a sentence that explains it seems like a a nice thing. 

### ReproNim Webinar Series
Our ReproNim ‘First Fridays’ monthly Webinar Series features important efforts in reproducibility, from both ReproNim and others.

My first instinct would be to underline/hyperlink 'ReproNim ‘First Fridays’ monthly Webinar Series" to the webinar series page, to clearly differentiate it from the youtube link in the 'Join the ReproNim Community' section.

I can submit an issue if the idea sounds ok and that would be an easier way to process it.

**Comment by asmacdo** [comment]
I haven't added this section, since I put the webinars in `about us` section, so there will be a button on the left bar.

IMO About us isnt really a great fit for this, but it made the most sense today, since the Resources is pretty much just documentation.

**Comment by asmacdo** [comment]
Julie and I discussed today, we are going to leave as-is, since the webinars are listed on the left bar of the about us page
