### ISSUE TITLE
Training section is ready

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#63]
I did all my changes on the 'Teach' page, because that is the one section that has a lot of training module materials on the back end of the site with custom html sutff, so per our discussion last week, I understood your recommendation to be 'lets use this page as a live link (I think) from the current site.

the page is here: https://www.repronim.org/teach.html

**Comment by asmacdo** [comment]
Agreed-- the plan is to not port the teach page at this time since it will be a bit of a project. So the outcome of this issue is only to add a link to that page. 

Prior to closing this issue, we should create a new issue to port that page, and label it as "Phase 2" or similar.

**Comment by asmacdo** [comment]
Google doc draft https://docs.google.com/document/d/1xE2HThK6gl7zIgXqwfIc-bXKwcbRBojyi0pzXBuTvnA/edit?pli=1&tab=t.0
