### ISSUE TITLE
ReproPond/ReproLake tutorial

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#67]
From Maryann's email (December 16):

> We’re still working on the one from Sean to make it more accessible, but I think at this point we should post what we have.  https://docs.google.com/spreadsheets/d/1wrmiDYzfpfGt9br4Vuwsm0b25IbF214mjTA5OkfbpXA/edit?gid=0#gid=0

**Comment by asmacdo** [comment]
Thats a link to the spreadsheet-- I think this is the actual link. https://docs.google.com/document/d/1wdTsTowf-uzu4LSAvEJ_GDbI9f1WeBSjm2BXcQMAgrI/edit?tab=t.0#heading=h.n5hxqddphuzz

@memartone there are lots of suggestions in there-- we need to accept or reject them before I can add to the site.
