### ISSUE TITLE
Git tutorial

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/repronim.org#69]
Tutorial from Dorota

**Comment by dnkennedy** [comment]
Regarding NeuroDocker, I presume...

**Comment by chaselgrove** [comment]
https://docs.google.com/document/d/1akNIG-h7Ozs_R0k9KGlxg8sTdnKbp2g8JCtw7YBL-SM/edit?tab=t.0#heading=h.k1s2szmakxpb

Still needs to be finalized.

**Comment by chaselgrove** [comment]
https://docs.google.com/document/d/1akNIG-h7Ozs_R0k9KGlxg8sTdnKbp2g8JCtw7YBL-SM/edit?tab=t.0#heading=h.k1s2szmakxpb
