### ISSUE TITLE
Request removal of one line in Participate section, and a question

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#91]
One Request ---

Please remove the line and link for reporting site errors- that's to set aside for now 

From the message you sent me about syntax, the line to remove is this one:
To report site errors, please file an issue at our [github repo](https://github.com/ReproNim/repronim.org)

and One Question!

What is the appropriate mechanism for letting you know when ok to merge?

(The revised spacing in the Calendar section is great.)

**Comment by asmacdo** [comment]
@juliebates I've opened the PR to do that. https://github.com/ReproNim/repronim.org/pull/92/


To review:

From the  the Files changed tab, click "Review changes" (on the right)
![image](https://github.com/user-attachments/assets/5521527e-862a-41cb-ab09-cc14d3f1a165)

If you don't have the option to "Approve" you can just add a comment that says it looks good to you, or whatever.

**Comment by asmacdo** [comment]
I'll wait to merge until you have the opportunity to try this out. 

IMHO, I think we should encourage folks to file issues, but since we discussed this in the committee meeting, I'll just go with the committee decision, we can always add it back later if we change our minds.

**Comment by juliebates** [comment]
Hmmm. I see and click on the Review Changes button, but I don't see anything, it is either as if it has taken a screen shot without the content, or is such a circumscribed view that no lines show up on the screen. Is there another way to view it? Or maybe I am missing something!

**Comment by juliebates** [comment]
On the line removal - yes, I took it off for now for the committee reasoning as well
I agree though, it does seem like something easy to add back in if we want it

**Comment by juliebates** [comment]
I'm looking at the view again, it just shows 'Remove the issue link' so I still think the preview isn't focused in the right place, at least not to let me view what the Participate screen would look like if the line were removed.

**Comment by asmacdo** [comment]
@juliebates above is a screen shot I took just to show where the buttons are. youll need to start from the PR [here](https://github.com/ReproNim/repronim.org/pull/92)

**Comment by juliebates** [comment]
Ahh, thank you!  That's nice. Great, All set to Merge!
