### ISSUE TITLE
Link Blog to new blog page

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#94]
I thought that Christian had produce a new blog page for us?  

[The ReproNim Blog](https://repronim.wordpress.com/)

**Comment by asmacdo** [comment]
@memartone maybe you were thinking of the "news" page https://dev.repronim.org/about/news/

We don't have a blog page, but the blog is already linked in participate https://dev.repronim.org/participate/

**Comment by memartone** [comment]
Yes, I thought we were going to combine news and blogs together on the same page but I will defer to @chaselgrove on this.

**Comment by chaselgrove** [comment]
Yes, it would be good to point to the new one since it's a slightly different way of organizing the blog and news content.  I do this in #112.
