### ISSUE TITLE
ReproSchema tutorial

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/repronim.org#95]
Yibei provided a draft tutorial, I wonder what happened to that?

https://docs.google.com/document/d/1psXPQnrERAKBo7I1OAi1d1ip1ZnOWSYw3YZej0RP_X8/edit?usp=sharing

To which Maryann commented: "I’d like it organized more like we have our other ones:  Challenge, Exercise, Before you start, Step by Step.  Others used slightly different headings, but I think it is better not to deviate too far.

So we can either do this or we can request edits from Yibei."

But I'm not sure if it went any further than that. Sorry if I dropped the ball on that communication...

**Comment by chaselgrove** [comment]
Needs to be reworked to fit our tutorial structure.  I'll follow up with Yibei.
