### ISSUE TITLE
Edit Collaborator and Participate section 

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#96]
I think that the Collaborators section https://main--repronim.netlify.app/about/collaborators/ should be redone as follows:

1)  Remove the “Participate in ReproNim” section.  (we already have a tab so I don’t want to duplicate)
2)  Move the first paragraph from that section beginning "ReproNim is dedicated to making neuroimaging…”  to the Participate tab https://main--repronim.netlify.app/participate/
3)  Move the second paragraph on collaborators under the “Collaborators” section.  Edit the text to indicate the role of Collaborative projects in P41 Centers.
4)  Move the third paragraph on service projects under the “Service” section.  Edit the text to indicate the role of Service projects in P41s.

**Comment by asmacdo** [comment]
FYI @memartone dev.repronim.org is identical to repronim.netlify.app, no need to use that link anymore, but its equivalent so no big deal)

> Edit the text to indicate the role of Collaborative projects in P41 Centers.

I'm not clear on what this means

**Comment by asmacdo** [comment]
From @juliebates email:

"The P41 interacts with Collaborative Projects (CPs) that serve as technology drivers, users, and testbeds for the cutting-edge technology developed in TR&D projects."

This could be modified slightly for the general audience I think, to something like :

 

The P41 Center Collaborative Projects (CPs) serve as technology drivers, users, and testbeds for the cutting-edge technology developed in Technology, Research and Development  projects."

 

 

And: "The P41 Center provides their technology to Service Projects (SPs) that serve as users of the well-developed and stable technologies of the Center."

**Comment by juliebates** [comment]
Sorrym I hadn't seen these question, I didn't see a little comment indicator next to the issue! 

I have a couple of additional notes/suggestions from Dave. He agreed the big Participate section was distracting. He liked moving paragraph 2 (from that 3 paragraph section To the Collaborators section of the page, and he also like moving paragraph #3 to the Service Projects section. In addition, he suggested adding just a single line at the bottom of the Collaborators page to invite people to contact us if interested in becoming a ReproNim Collaborating or Service Project - something along the lines of:
 [Contact us] if you are interested in becoming a ReproNim Collaborating or Service Project

**Comment by juliebates** [comment]
One more comment from Dave, he was on the fence about whether to move paragraph #1 from the Participate section TO the Participate tab, as it seemed very 'beefy' as an addition to what is currently a streamlined page. That is food for thought. It does support removing that paragraph from the Collaborators page, it more raises the question of whether to put it anywhere else

**Comment by juliebates** [comment]
Dave asked to put it at the bottom, that is why I suggested it
- we are listing/reporting our current projects, and then inviting folks to join if intereested
